In [5]:
import numpy as np
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [6]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("vectorized version: " + str(1000 * (toc-tic)) + " ms")

c = 0
tic = time.time()

for i in range(1000000):
    c += a[i] * b[i]

toc = time.time()
print(c)
print("forLoop version: " + str(1000 * (toc-tic)) + " ms")




249985.26455429947
vectorized version: 22.301197052001953 ms
249985.2645543088
forLoop version: 377.78615951538086 ms


In [9]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c)

[[ 2.95169082  1.02861975  0.78974663]
 [-0.43999497 -0.94745595 -0.79514022]]


In [10]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [13]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
print(a)
print(b)
c = a*b
print(c)

[[-0.13939027 -1.58745641  0.11979445]
 [ 0.56856203  0.07354535 -0.0410286 ]
 [-0.54945085  0.22052253  1.19139463]]
[[-0.15308136]
 [ 1.79377795]
 [-0.80481121]]
[[ 0.02133805  0.24300999 -0.0183383 ]
 [ 1.01987403  0.13192403 -0.0735962 ]
 [ 0.4422042  -0.17747901 -0.95884775]]
